sudo: required
services:
  - docker
language: go
go: 1.7
install:
  - go get github.com/Masterminds/glide
  - make deps
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - make docker
script:
  - make
  - make lint
  - make test
before_deploy: ./ci/make-bintray-descriptor
deploy:
  provider: bintray
  file: ./bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  skip_cleanup: true
  on:
    tags: true
