sudo: required
services:
  - docker
language: go
go: 1.7
install:
  - curl https://glide.sh/get | sh
  - make deps
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - make docker
script:
  - make lint
  - make test
